
export const banks = [
	{ bankname: "9mobile 9Payment Service Bank", slug: "9mobile-9payment-service-bank-ng", code: "120001" },
	{ bankname: "Abbey Mortgage Bank", slug: "abbey-mortgage-bank", code: "801" },
	{ bankname: "Above Only MFB", slug: "above-only-mfb", code: "51204" },
	{ bankname: "Abulesoro MFB", slug: "abulesoro-mfb-ng", code: "51312" },
	{ bankname: "Access Bank", slug: "access-bank", code: "044" },
	{ bankname: "Access Bank (Diamond)", slug: "access-bank-diamond", code: "063" },
	{ bankname: "Accion Microfinance Bank", slug: "accion-microfinance-bank-ng", code: "602" },
	{ bankname: "Ahmadu Bello University Microfinance Bank", slug: "ahmadu-bello-university-microfinance-bank-ng", code: "50036" },
	{ bankname: "Airtel Smartcash PSB", slug: "airtel-smartcash-psb-ng", code: "120004" },
	{ bankname: "AKU Microfinance Bank", slug: "aku-mfb", code: "51336" },
	{ bankname: "ALAT by WEMA", slug: "alat-by-wema", code: "035A" },
	{ bankname: "Amegy Microfinance Bank", slug: "amegy-microfinance-bank-ng", code: "090629" },
	{ bankname: "Amju Unique MFB", slug: "amju-unique-mfb", code: "50926" },
	{ bankname: "AMPERSAND MICROFINANCE BANK", slug: "ampersand-microfinance-bank-ng", code: "51341" },
	{ bankname: "Aramoko MFB", slug: "aramoko-mfb", code: "50083" },
	{ bankname: "ASO Savings and Loans", slug: "asosavings", code: "401" },
	{ bankname: "Astrapolaris MFB LTD", slug: "astrapolaris-mfb", code: "MFB50094" },
	{ bankname: "Bainescredit MFB", slug: "bainescredit-mfb", code: "51229" },
	{ bankname: "Banc Corp Microfinance Bank", slug: "banc-corp-microfinance-bank-ng", code: "50117" },
	{ bankname: "Bowen Microfinance Bank", slug: "bowen-microfinance-bank", code: "50931" },
	{ bankname: "Branch International Financial Services Limited", slug: "branch", code: "FC40163" },
	{ bankname: "Carbon", slug: "carbon", code: "565" },
	{ bankname: "CASHCONNECT MFB", slug: "cashconnect-mfb-ng", code: "865" },
	{ bankname: "CEMCS Microfinance Bank", slug: "cemcs-microfinance-bank", code: "50823" },
	{ bankname: "Chanelle Microfinance Bank Limited", slug: "chanelle-microfinance-bank-limited-ng", code: "50171" },
	{ bankname: "Chikum Microfinance bank", slug: "chikum-microfinance-bank-ng", code: "312" },
	{ bankname: "Citibank Nigeria", slug: "citibank-nigeria", code: "023" },
	{ bankname: "Consumer Microfinance Bank", slug: "consumer-microfinance-bank-ng", code: "50910" },
	{ bankname: "Corestep MFB", slug: "corestep-mfb", code: "50204" },
	{ bankname: "Coronation Merchant Bank", slug: "coronation-merchant-bank-ng", code: "559" },
	{ bankname: "County Finance Limited", slug: "county-finance-limited", code: "FC40128" },
	{ bankname: "Crescent MFB", slug: "crescent-mfb", code: "51297" },
	{ bankname: "Dot Microfinance Bank", slug: "dot-microfinance-bank-ng", code: "50162" },
	{ bankname: "Ecobank Nigeria", slug: "ecobank-nigeria", code: "050" },
	{ bankname: "Ekimogun MFB", slug: "ekimogun-mfb-ng", code: "50263" },
	{ bankname: "Ekondo Microfinance Bank", slug: "ekondo-microfinance-bank-ng", code: "098" },
	{ bankname: "Eyowo", slug: "eyowo", code: "50126" },
	{ bankname: "Fairmoney Microfinance Bank", slug: "fairmoney-microfinance-bank-ng", code: "51318" },
	{ bankname: "Fidelity Bank", slug: "fidelity-bank", code: "070" },
	{ bankname: "Firmus MFB", slug: "firmus-mfb", code: "51314" },
	{ bankname: "First Bank of Nigeria", slug: "first-bank-of-nigeria", code: "011" },
	{ bankname: "First City Monument Bank", slug: "first-city-monument-bank", code: "214" },
	{ bankname: "FirstTrust Mortgage Bank Nigeria", slug: "firsttrust-mortgage-bank-nigeria-ng", code: "413" },
	{ bankname: "FLOURISH MFB", slug: "flourish-mfb-ng", code: "50315" },
	{ bankname: "FSDH Merchant Bank Limited", slug: "fsdh-merchant-bank-limited", code: "501" },
	{ bankname: "Gateway Mortgage Bank LTD", slug: "gateway-mortgage-bank", code: "812" },
	{ bankname: "Globus Bank", slug: "globus-bank", code: "00103" },
	{ bankname: "GoMoney", slug: "gomoney", code: "100022" },
	{ bankname: "Goodnews Microfinance Bank", slug: "goodnews-microfinance-bank-ng", code: "50739" },
	{ bankname: "Greenwich Merchant Bank", slug: "greenwich-merchant-bank-ng", code: "562" },
	{ bankname: "Guaranty Trust Bank", slug: "guaranty-trust-bank", code: "058" },
	{ bankname: "Hackman Microfinance Bank", slug: "hackman-microfinance-bank", code: "51251" },
	{ bankname: "Hasal Microfinance Bank", slug: "hasal-microfinance-bank", code: "50383" },
	{ bankname: "Heritage Bank", slug: "heritage-bank", code: "030" },
	{ bankname: "HopePSB", slug: "hopepsb-ng", code: "120002" },
	{ bankname: "Ibile Microfinance Bank", slug: "ibile-mfb", code: "51244" },
	{ bankname: "Ikoyi Osun MFB", slug: "ikoyi-osun-mfb", code: "50439" },
	{ bankname: "Ilaro Poly Microfinance Bank", slug: "ilaro-poly-microfinance-bank-ng", code: "50442" },
	{ bankname: "Imowo MFB", slug: "imowo-mfb-ng", code: "50453" },
	{ bankname: "Infinity MFB", slug: "infinity-mfb", code: "50457" },
	{ bankname: "Jaiz Bank", slug: "jaiz-bank", code: "301" },
	{ bankname: "Kadpoly MFB", slug: "kadpoly-mfb", code: "50502" },
	{ bankname: "Keystone Bank", slug: "keystone-bank", code: "082" },
	{ bankname: "Kredi Money MFB LTD", slug: "kredi-money-mfb", code: "50200" },
	{ bankname: "Kuda Bank", slug: "kuda-bank", code: "50211" },
	{ bankname: "Lagos Building Investment Company Plc.", slug: "lbic-plc", code: "90052" },
	{ bankname: "Links MFB", slug: "links-mfb", code: "50549" },
	{ bankname: "Living Trust Mortgage Bank", slug: "living-trust-mortgage-bank", code: "031" },
	{ bankname: "Lotus Bank", slug: "lotus-bank", code: "303" },
	{ bankname: "Mayfair MFB", slug: "mayfair-mfb", code: "50563" },
	{ bankname: "Mint MFB", slug: "mint-mfb", code: "50304" },
	{ bankname: "Moniepoint MFB", slug: "moniepoint-mfb-ng", code: "50515" },
	{ bankname: "MTN Momo PSB", slug: "mtn-momo-psb-ng", code: "120003" },
	{ bankname: "OPay Digital Services Limited (OPay)", slug: "paycom", code: "00711" },
	{ bankname: "Optimus Bank Limited", slug: "optimus-bank-ltd", code: "107" },
	{ bankname: "Paga", slug: "paga", code: "100002" },
	{ bankname: "PalmPay", slug: "palmpay", code: "999991" },
	{ bankname: "Parallex Bank", slug: "parallex-bank", code: "104" },
	{ bankname: "Parkway - ReadyCash", slug: "parkway-ready-cash", code: "311" },
	{ bankname: "Paycom", slug: "paycom", code: "999992" },
	{ bankname: "Peace Microfinance Bank", slug: "peace-microfinance-bank-ng", code: "50743" },
	{ bankname: "Personal Trust MFB", slug: "personal-trust-mfb-ng", code: "51146" },
	{ bankname: "Petra Mircofinance Bank Plc", slug: "petra-microfinance-bank-plc", code: "50746" },
	{ bankname: "Platinum Mortgage Bank", slug: "platinum-mortgage-bank-ng", code: "268" },
	{ bankname: "Polaris Bank", slug: "polaris-bank", code: "076" },
	{ bankname: "Polyunwana MFB", slug: "polyunwana-mfb-ng", code: "50864" },
	{ bankname: "PremiumTrust Bank", slug: "premiumtrust-bank-ng", code: "105" },
	{ bankname: "Providus Bank", slug: "providus-bank", code: "101" },
	{ bankname: "QuickFund MFB", slug: "quickfund-mfb", code: "51293" },
	{ bankname: "Rand Merchant Bank", slug: "rand-merchant-bank", code: "502" },
	{ bankname: "Refuge Mortgage Bank", slug: "refuge-mortgage-bank", code: "90067" },
	{ bankname: "Rigo Microfinance Bank Limited", slug: "rigo-microfinance-bank-limited-ng", code: "51286" },
	{ bankname: "ROCKSHIELD MICROFINANCE BANK", slug: "rockshield-microfinance-bank-ng", code: "50767" },
	{ bankname: "Rubies MFB", slug: "rubies-mfb", code: "125" },
	{ bankname: "Safe Haven MFB", slug: "safe-haven-mfb-ng", code: "51113" },
	{ bankname: "Safe Haven Microfinance Bank Limited", slug: "safe-haven-microfinance-bank-limited-ng", code: "951113" },
	{ bankname: "SAGE GREY FINANCE LIMITED", slug: "sage-grey-finance-limited-ng", code: "40165" },
	{ bankname: "Shield MFB", slug: "shield-mfb-ng", code: "50582" },
	{ bankname: "Solid Allianze MFB", slug: "solid-allianze-mfb", code: "51062" },
	{ bankname: "Solid Rock MFB", slug: "solid-rock-mfb", code: "50800" },
	{ bankname: "Sparkle Microfinance Bank", slug: "sparkle-microfinance-bank", code: "51310" },
	{ bankname: "Stanbic IBTC Bank", slug: "stanbic-ibtc-bank", code: "221" },
	{ bankname: "Standard Chartered Bank", slug: "standard-chartered-bank", code: "068" },
	{ bankname: "Stellas MFB", slug: "stellas-mfb", code: "51253" },
	{ bankname: "Sterling Bank", slug: "sterling-bank", code: "232" },
	{ bankname: "Suntrust Bank", slug: "suntrust-bank", code: "100" },
	{ bankname: "Supreme MFB", slug: "supreme-mfb-ng", code: "50968" },
	{ bankname: "TAJ Bank", slug: "taj-bank", code: "302" },
	{ bankname: "Tanadi Microfinance Bank", slug: "tanadi-microfinance-bank-ng", code: "090560" },
	{ bankname: "Tangerine Money", slug: "tangerine-money", code: "51269" },
	{ bankname: "TCF MFB", slug: "tcf-mfb", code: "51211" },
	{ bankname: "Titan Bank", slug: "titan-bank", code: "102" },
	{ bankname: "Titan Paystack", slug: "titan-paystack", code: "100039" },
	{ bankname: "U&C Microfinance Bank Ltd (U AND C MFB)", slug: "uc-microfinance-bank-ltd-u-and-c-mfb-ng", code: "50840" },
	{ bankname: "Uhuru MFB", slug: "uhuru-mfb-ng", code: "MFB51322" },
	{ bankname: "Unaab Microfinance Bank Limited", slug: "unaab-microfinance-bank-limited-ng", code: "50870" },
	{ bankname: "Unical MFB", slug: "unical-mfb", code: "50871" },
	{ bankname: "Unilag Microfinance Bank", slug: "unilag-microfinance-bank-ng", code: "51316" },
	{ bankname: "Union Bank of Nigeria", slug: "union-bank-of-nigeria", code: "032" },
	{ bankname: "United Bank For Africa", slug: "united-bank-for-africa", code: "033" },
	{ bankname: "Unity Bank", slug: "unity-bank", code: "215" },
	{ bankname: "VFD Microfinance Bank Limited", slug: "vfd", code: "566" },
	{ bankname: "Waya Microfinance Bank", slug: "waya-microfinance-bank-ng", code: "51355" },
	{ bankname: "Wema Bank", slug: "wema-bank", code: "035" },
	{ bankname: "Zenith Bank", slug: "zenith-bank", code: "057" },
];



export const goalOptions = [
    { id: 'automate-my-sales-and-orders', label: 'Automate my sales and orders' },
    { id: 'get-well-detailed-analytics', label: 'Get well-detailed analytics' },
    { id: 'instant-notification-on-new-order', label: 'Instant notification on new order' },
    { id: 'create-store-website-and-run-sales', label: 'Create store website and run sales' },
    { id: 'record-new-customer-for-future-sales', label: 'Record new customer for future sales' },
    { id: 'track-store-visitor-and-purchases', label: 'Track store visitor and purchases' },
    { id: 'record-daily-sales-and-expenses', label: 'Record Daily sales and expenses' },
    { id: 'manage-inventory-and-track-low-stocks', label: 'Manage inventory and track low stocks' },
]; 